spring:
  application:
    name: feign-server
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true

#turbine:
#  app-config: service-customer
#  combine-host-port: true
#  cluster-name-expression: "'default'"
